owner: Pierre Mallinjoud
email: pierre.mallinjoud@gmail.com
github: ellipsephp
twitter: pmallinj

sass:
    style: compressed

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:name/
