title: Blog title
description: Blog description
locale: en_US
image: blog-image.png
owner: Owner
email: owner@example.com
github: github_handle
twitter: twitter_handle

sass:
    style: compressed

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:name/
