title: Ellipse php blog
description: Ellipse php blog
locale: en_US
image: psr-15.png
owner: Pierre Mallinjoud
email: pierre.mallinjoud@gmail.com
github: ellipsephp
twitter: pmallinj
disqus: pmall-github-io

sass:
    style: compressed

plugins:
  - jekyll-feed
