title: Blog title
owner: Owner
email: owner@example.com
github: github_handle
twitter: twitter_handle

sass:
    style: compressed

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:name/
